### ISSUE TITLE
[Feature Request]: Qt bindings/wrapper

### ISSUE THREAD

**Issue by RJVB** [VcDevel/Vc#166]
This is a suggestion based on a thought that came up when I saw a Qt-based multimedia player using QByteArray instances as the internal vector for audio and probably other 1-D data.

I don't know of any extension of Qt's relevant container classes that makes it possible to use them "as is" in vector operations that will be executed using SIMD instructions.

What I'm thinking of is bindings or wrapper classes that can act as more or less straight drop-ins for the stock container classes, along the lines what the old MacSTL library (fork: https://github.com/RJVB/MacSTL) did for stl::valarray and family.

Not so long ago I'd have found this a nice side-project to start tinkering with myself, nowadays my priorites are such that I'll start with just dropping the idea on here to see if it gets picked up. I think it'd be useful, both for developers using Qt and for Vc to reach a wider audience.

**Comment by mattkretz** [comment]
Thank you for the suggestion. I don't think I understood the idea yet, though. The `Vector` class (or `datapar` in the latest std C++ proposal) models standard C++ container interfaces to some degree. I have chosen not to support e.g. `begin()` & `end()` - i.e. iterators - since they would have to be input iterators (the union hack in MacSTL is an aliasing violation of the standard) and suggest a usage that is not explicitly parallel.
Could you make an example of the interface you'd like to see?

**Comment by mattkretz** [comment]
Here's what I understood you're suggesting:
Create e.g. `class QSimdVector<T> : public QVector<T>`. Have the derived class add arithmetic, bitwise and relational operators as well as non-member math functions to the base (e.g. QVector<T>) interface.

I think that's the wrong angle to solve the problem. Containers should be things that store data, not more. I don't want anyone to think that `a * b + c` is a good idea for large number of elements. Instead the programmer must see that he can only work on small chunks of the container at a time. And then decide how to parallelize or serialize the iteration of the whole container. There can be (and should be) convenience functions for iterating over a container using SIMD vectors. See https://wg21.link/p0350 for the plan. For those parallel algorithms to work with Qt containers the containers only need to implement the STL concepts, which I think they do already, no?

**Comment by RJVB** [comment]
On Wednesday May 10 2017 05:15:23 Matthias Kretz wrote:

>I think that's the wrong angle to solve the problem. 

What problem? :)

>Containers should be things that store data, not more. I don't want anyone to think that `a * b + c` is a good idea for large number of elements.

Why not? You're the expert, but I don't understand the Vc documentation as "you can now calculate with vector variables as if they were scalars and get a boost from SIMD" with an added "but you can only do that for small chunks at a time".

QVector is called a container because it provides little more than container features. But in the end an array or vector (in the mathematical sense) is a container too and yet they also provide operations that do things with rather than on the contained data.

>Instead the programmer must see that he can only work on small chunks of the container at a time.

I think one should distinguish 2 classes of programmer here, roughly. On the one hand there are those who write software others use to get optimum performance for what they must do. They'd include those who develop products like MatLab that aim to allow things like `a * b + c` with arbitrary vectors and optimum performance. On the other hand there are those who write software because they have a problem to solve and they're interested in the optimum balance between their code's performance and the time they spend writing it instead of using it. 

>For those parallel algorithms to work with Qt containers the containers only need to implement the STL concepts, which I think they do already, no?

Possibly, they probably do judging from what I've seen and remember of comparable STL classes.

R.

**Comment by mattkretz** [comment]
> What problem? :)

"Qt bindings/wrapper" i.e. making it easier for Qt users to work with SIMD. Isn't that the problem your suggestion is trying to solve?

> Why not?

1. API design. Don't conflate too many things into one entity. E.g. look at the names. Does the name "container" imply arithmetic operations?
2. Cache efficiency. Don't iterate over large amounts of data doing little work. Use small working-set sizes and do as much work on them as you can. Memory throughput is typically the limiting factor in our codes, not compute throughput.

>  an array or vector (in the mathematical sense) is a container too and yet they also provide operations that do things with rather than on the contained data

They are not a container in the sense of the concept they are implementing. They do contain elements that can be accessed individually and thus have some container-like properties. But that's not the design goal, it's a coincidence following from the goal of implementing a mathematical entity.

> one should distinguish 2 classes of programmer

* The ones who don't care for optimum performance probably don't care for Vc and SIMD execution.
* The ones who want matlab style programming should use a numerical library, which could be implemented on top of Vc. Those users don't really have to see SIMD vector objects at all. Qt is not aiming to be a numerical library the last I checked.

But there are certainly users who are performance sensitive. Those should certainly have an easy way to explicitly vectorize their codes. I think Vc in its current form (and upcoming features) solves that. I do certainly have lots of ideas to improve things. But I sadly don't have enough clones of myself to do the work.

That said, I'll close this issue because I believe the suggestion on extending containers is the wrong direction and the right direction (while not fully done) is already implemented.
