### ISSUE TITLE
move constructor missing on ElementReference

### ISSUE THREAD

**Issue by chr-engwer** [VcDevel/Vc#168]
The ElementReference contains a
```
Vc_INTRINSIC ElementReference(const ElementReference &) = delete;
```
this seems to imply (didn't check the standard...) that the move constructor is also not available.
This poses some issues is our code. We provide several helper functions, which are specialized for different SIMD types, for example a `lane` function, which allows immediate access to a particular lane. This is specialized for scalar C++ types and for SIMD types. This function fails since the introduction of `ElementReference` (we didn't update in a while...) and the obvious fix (auto return type and std::move) does not work, because the move constructor is missing.

Adding
```
Vc_INTRINSIC ElementReference(ElementReference &&) = default;
```
fixed everything for us. I'm not sure about the reasons not to include the move constructor...
Can this fix be included? Or what are the reasons to prohibit this? I understand that we want to avoid copying references, but a `std::move` should be ok.

**Comment by mattkretz** [comment]
The semantics of ElementReference are modeled after subscripts on Clang vector builtins. I.e. you can only assign to them directly, never take an address of it. This design is also the guidance from the C++ committee on this issue.
In previous Vc versions the subscript operator returned a "proper" lvalue reference. This is not implementable with standard C++, as it requires special measures to turn strict aliasing optimizations off. GCC and Clang provide this via the ``[[gnu::may_alias]]`` attribute. But note that this attribute can get lost in certain situations, so that I'd like to keep use of this workaround down to a minimum and never leak such ``may_alias`` types through the public interface.
So why no move on the reference wrapper? Technically, I don't see an issue with it either. But from an interface design view there's a good reason. Consider what happens when you can work with lvalues of ``ElementReference``: you can store them and keep them around for as long as the ``Vector`` object lives. While you can do this for `std::array` too, the situation is slightly different for ``Vector``, since ``ElementReference`` implements type-punning.

However, IIUC, all that you really need is guaranteed copy-elision (i.e. C++17). You just want to return an ``ElementReference`` object from a wrapper around ``Vector::operator[]``, right? I expect that this'll just work fine when you flip the ``-std=`` switch. See here: https://godbolt.org/g/uJ2eyM

Hmm, then again, C++17 enables users to create ``ElementReference`` lvalues through guaranteed copy elision. So maybe it is a sensible idea to provide the move ctor until users switch to C++17. Any opinion?

**Comment by chr-engwer** [comment]
While I understand you argument regarding the life time of objects, I don't think this is something we should enforce here. In general many interfaces allow access via a mutable reference and it is always something where the documentation has to be clear regarding the lifetime, but the compiler can't do the work for you.

In the case of SIMD data structures, I think it is the exact right thing to go via the wrapper, as there might even be types where you can't provide a reference to `double` or `float` due to aliasing. On the other hand we want it behave like a reference and this implies that there is some way of copying or moving the thing around. copying might become costly, some is imho preferable. You reference the C++17 standard, where copy-elision allows me to avoid the copy immediately due to compiler support. But does this really change anything? Internally the compiler does basically a move, so I think it would be better to directly allow the move. It is a clear construct, it can't be done implicitly like in the case of a reference, so users should be aware of the problem (as they explicitly have to write `std::move` instead of a simple assignment) and it avoid additional overhead.

**Comment by chr-engwer** [comment]
I can prepare a patch... (including documentation)

**Comment by chr-engwer** [comment]
I created an according PR...
