### ISSUE TITLE
conversion error testing static_simd_cast

### ISSUE THREAD

**Issue by rolandschulz** [VcDevel/Vc#185]
Vc master, Linux, GCC7.2

```cpp
namespace simd = Vc;
using SimdFloat = simd::native_simd<float>;
using SimdInt = simd::native_simd<int>;
SimdInt g(SimdFloat a)
{
     //return simd::static_simd_cast<SimdInt>(a); //works                                                                                                                                                                                     
    return simd::static_simd_cast<int>(a);
}
```

-march=core-avx2:
`test.cc:25:39: error: could not convert 'Vc::v2::static_simd_cast(const Vc::v2::simd<U, A>&) [with T = int; U = float; A = Vc::v2::simd_abi::avx; R = Vc::v2::simd<int, Vc::v2::simd_abi::fixed_size<8> >]()' from 'Vc::v2::simd<int, Vc::v2::simd_abi::fixed_size<8> >' to 'SimdInt {aka Vc::v2::simd<int, Vc::v2::simd_abi::avx>}'
`
-msse4.1:
`test.cc:25:39: error: could not convert 'Vc::v2::static_simd_cast(const Vc::v2::simd<U, A>&) [with T = int; U = float; A = Vc::v2::simd_abi::sse; R = Vc::v2::simd<int, Vc::v2::simd_abi::fixed_size<4> >]()' from 'Vc::v2::simd<int, Vc::v2::simd_abi::fixed_size<4> >' to 'SimdInt {aka Vc::v2::simd<int, Vc::v2::simd_abi::sse>}'`

In each case the size should be the the native size and thus it should convert without any problem.

It works with dimsum/libcxx

**Comment by mattkretz** [comment]
Look at [simd.casts] in https://wg21.link/p0214:
> If `is_simd_v<T>` is `true`, the return type is `T`. Otherwise, if either `U` is `T` or `U` and `T` are integral types that only differ in signedness, the return type is `simd<T, Abi>`. Otherwise, the return type is `simd<T, simd_abi::fixed_size<simd<U, Abi>::size()>>`.

`is_simd_v<int>` is `false`, and `int` is neiter `float`, nor are both integral types. Thus, the return type is `simd<T, simd_abi::fixed_size<simd<U, Abi>::size()>>`. However, `fixed_size` is not implicitly convertible to native ABIs. [simd.ctor]

That's a bug in dimsum, which AFAIK is due to dimsum not supporting `fixed_size`.

If you believe there's a problem in the specification please let me know how you would expect implicit conversions to work instead. This will be important feedback when we want to move the TS into the standard proper. Feel free to take your time with figuring out your opinion, though.
