### ISSUE TITLE
why can't one use int_m to conditionally assign float_v?

### ISSUE THREAD

**Issue by niklasnolte** [VcDevel/Vc#232]
`Vc::where(some_int_m) | some_float_v += 1;`

What is the fundamental reason this does not work without simd_casting?
This keeps me from conditionally assigning custom structs with overloaded `operator+=`, like some `SIMD::Matrix` which has as elements `float_v`s;

**Comment by mattkretz** [comment]
Because it wouldn't be portable. `int_m::size() == float_v::size()` is not guaranteed to be `true` on all targets (e.g. AVX without AVX2). You'd need to use `fixed_size_simd(_mask)<int, float_v::size()>` to have an integer type that works portably. AFAIR that one still doesn't convert implicitly but I'd be open to a changing it (cf. https://github.com/mattkretz/wg21-papers/issues/3)

**Comment by niklasnolte** [comment]
thanks for the info. I think loosening the conversion rules would be great already
