### ISSUE TITLE
1.4.2 - README up to date

### ISSUE THREAD

**Issue by agheata** [VcDevel/Vc#264]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
         1.4.2             |         all         |        all            |       -         |           -          |

## Testcase
```cpp
```

## Expected Results
README.md is up to date

**Comment by bernhardmgruber** [comment]
At the beginning, the README.md mentions `std::simd`. We could mention here that libstdc++ with GCC11 ships an experimental implementation.

We probably need a new bullet point under Documentation for the doxygen of 1.4.2.

Does the freenode IRC channel for vc still exist? Otherwise we should remove it. Same question for the Vc mailing list.

**Comment by agheata** [comment]
Agreed with the std::simd mention. It looks to me that the makeRelease.sh script is supposed to deal by itself with the creation of the 1.4.2 bullet, copy the generated doxygen docs in a local clone of vcdevel.github.io and push, [see here]( https://github.com/VcDevel/Vc/blob/83e99cd6d2c5645248652ccab0ab73ffea614b27/makeRelease.sh#L60L68)
The problem is that this won't work without the right credentials (customized to be done by @mattkretz )
