### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by vks** [VcDevel/Vc#72]
Some files still claim to be licensed as GPL, for example [here](https://github.com/VcDevel/Vc/blob/master/include/Vc/Memory) or [here](https://github.com/VcDevel/Vc/blob/master/include/Vc/Vc). Also, the main directory includes the LGPL but not the BSD license, which might be confusing.

[This file](https://github.com/VcDevel/Vc/blob/master/include/Vc/array) is from the standard library and GPL3 with the runtime exception, which might be problematic.

**Comment by mattkretz** [comment]
Good points. Thanks for checking. I'll clean those up (my script obviously was flawed...).

Regarding the `std::array` copy, you raise an important question. AFAIK, for most users that wouldn't be a problem, otherwise using GCC would be a problem already. Then again, I probably shouldn't state that all code in Vc is BSD. Maybe I could also just fork `Vc::array` from libc++ to make the license more compatible.

**Comment by vks** [comment]
Forking from libc++ seems like the best option to me. It should be a drop-in replacement, no?

**Comment by mattkretz** [comment]
All I need is to add two `operator[]` overloads. Since `std::array` needs to be an aggregate I can't do it via inheritance (like I do for `std::vector`). Alright, I'll take a look at a libc++ fork then.
