### ISSUE TITLE
add build status image to README

### ISSUE THREAD

**Issue by vks** [VcDevel/Vc#84]
Now that #70 is merged, we could consider adding a build status image to the readme:

```markdown
[![Build Status](https://travis-ci.org/VcDevel/Vc.svg?branch=master)](https://travis-ci.org/VcDevel/Vc)
```

It would be probably better if the build is not failing. At the moment it looks like this:

[![Build Status](https://travis-ci.org/VcDevel/Vc.svg?branch=master)](https://travis-ci.org/VcDevel/Vc)

**Comment by mattkretz** [comment]
Actually, I'd change the link to directly get more information: `[![Build Status](https://travis-ci.org/VcDevel/Vc.svg?branch=master)](https://travis-ci.org/VcDevel/Vc/branches)`. Or is there a good reason not to do so?

**Comment by vks** [comment]
No, I just used the default suggested by Travis. I like your link because it clarifies which branches are failing.

**Comment by mattkretz** [comment]
After some getting used to how Travis integrates with github I'd rather not put this into the README. The README is still a textfile to be read with a texteditor, and this one would be very out of place. OTOH there is the Travis integration on https://github.com/VcDevel/Vc/branches, which is much better since it makes clear which branch is good and which one isn't.

**Comment by vks** [comment]
If you don't like the long link, you could also do something like this:

```markdown
[![Build Status][build-image]][travis]

[build-image]: https://travis-ci.org/VcDevel/Vc.svg?branch=master
[travis]: https://travis-ci.org/VcDevel/Vc/branches
```

Even if you don't like the image, I think Travis should be linked somewhere in the README.
