### ISSUE TITLE
Expression template for fma

### ISSUE THREAD

**Issue by chr-engwer** [VcDevel/Vc#88]
As `fma` is a typical pattern in mathematical codes. It would be very convenient to have some type of expression template to detect `fma` and automatically replace the code accordingly.

We currently use Vc as a drop-in replacement for double to allow vectorization of user-code, without requiring the user to learn about vectorization. But the user will not and can not use `fma`. The user will usually run the same code with just a vector of `double` and only when compiling a special way the vector of `double` with turn into a vector of `SimdArray`. This means that he has to write `x += a * y;` and can not use `fma` as it is not available for `double`.

**Comment by mattkretz** [comment]
The `fma` function exists only for the cases where you need the extra precision, independent of whether there's hardware support for it or not. You get FMA instructions automatically, even without expression template, because the compilers are free to transform individual multiply and add/sub operations into combined FMAs. This is controlled by the `-ffp-contract` compiler switch.

That said, I've seen at least GCC fail to do the optimization in some cases. But I thought I had all the necessary workarounds in place. Did you actually find missing FMAs? That would be a bug...

**Comment by chr-engwer** [comment]
I didn't look into the generated assembler. It was just my impression, that the compiler will not touch your code, as you explicitly use intrinics and thus will not be able to detect fused-multiply-add.

**Comment by mattkretz** [comment]
OK. In general the intrinsics should get translated into the internal vector types that are fully optimizable by the compiler. Therefore, intrinsics are not just direct wrappers for instructions. They carry semantics and the optimizer will make use of it. (Everything else is a bug/missed optimization.)
